import type { Metadata } from "next";

import { Providers } from "@/providers";
import { varelaRound } from "@/styles/fonts";
import "@/styles/globals.css";
import { cn } from "@/utils/cn";

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "flex min-h-svh flex-col items-center justify-between p-8 font-varela-round antialiased",
          varelaRound.variable,
        )}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
