import type { Metadata } from "next";

import { varelaRound } from "@/styles/fonts";
import "@/styles/globals.css";
import { cn } from "@/utils/cn";

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "font-varela-round flex min-h-svh flex-col items-center justify-between p-8 antialiased",
          varelaRound.variable,
        )}
      >
        {children}
      </body>
    </html>
  );
}
